### ISSUE TITLE
Conflict with System.Linq.Enumerable

### ISSUE THREAD

**Issue by fsateler** [atifaziz/Delegating#2]
The current implementation uses the name `Delegate` for the class holding all factory methods. This necessitates `using static Delegating.Delegate` because otherwise the compiler complains with error CS0104:

> 'Delegate' is an ambiguous reference between 'Delegating.Delegate' and 'System.Delegate'

However, `using static Delegating.Delegate` introduces another conflict:

```csharp
var empty = Enumerable.Empty<string>(); // CS0119: 'Delegate.Enumerable<T>(Func<IEnumerator<T>>)' is a method, which is not valid in the given context
```

To solve this (as library user), there are several options:

1. Rename via `using LinqEnumerable = System.Linq.Enumerable`
2. Fully specify the class name when invoking: `System.Linq.Enumerable.Empty<string>()`, or `Delegating.Disposable(action)`.
3. Import `Delegate` statically outside the namespace, but `Linq` inside the namespace:
```csharp

using static Delegating.Delegate;

namespace MyApp
{
    using static Delegating.Delegate;
    public static void Foo() => Enumerable.Empty<string>().Consume(); // Works!
}
```

However, I think none of the options is particularly attractive.

On the library side this can be fixed by:

1. Rename the `Delegate` class to `Delegating` and change instructions accordingly.
2. Rename the `Enumerable` method to something else.

I think option 1 is the most attractive, because backwards compatibility can be preserved by having `Delegate` forward all calls to `Delegating`.

What do you think?

**Comment by atifaziz** [comment]
> This necessitates `using static Delegating.Delegate` because otherwise the compiler complains…

This is not required. You can import `Delegate` explicitly via `using Delegate = Delegating.Delegate` and then the compiler won't complain anymore. `Delegate` without any namespace qualification will then resolve to the one from the `Delegating` namespace. Direct use of `System.Delegate` and its members is very rare and for those few times where it needs to be used in the same source file where Delegating is being used, one can either use namespace qualification or rename either class.

As for the options you list for the library user, there is yet another. The following example shows `System.Delegate`, `System.Linq.Enumerable`, LINQ and a static import of `Delegating.Delegate` living and working in harmony:

```c#
using System;
using System.Linq;
using System.Collections.Generic;
using static Delegating.Delegate;
using Enumerable = System.Linq.Enumerable;

namespace Test
{
    static class Program
    {
        static void Main()
        {
            var xs =
                from x in Enumerable(() => { return _(); IEnumerator<int> _()
                {
                    for (var x = 0; x < 20; x += 2)
                        yield return x;
                }})
                group x by x / 5 into g
                select g.Sum();
            
            Console.WriteLine(string.Join(", ", xs));

            var empty = Enumerable.Empty<int>();

            Action foo = () => Console.WriteLine(nameof(foo));
            Action bar = () => Console.WriteLine(nameof(bar));
            var foobar = (Action) Delegate.Combine(foo, bar);

            using (Disposable(() => Console.WriteLine("Disposed!")))
                foobar();
        }
    }
}
```

> Rename the `Delegate` class to `Delegating` and change instructions accordingly

I think this option can be left up to library users who are in the best position to resolve conflicts as they please. That is, the rename can be done via an alias like `using Delegated = Delegating.Delegate`.

Whether you do a static import of `Delegating.Delegate` is really a question of taste.

**Comment by fsateler** [comment]
> >This necessitates using static Delegating.Delegate because otherwise the compiler complains…
>
> This is not required. You can import Delegate explicitly via using Delegate = Delegating.Delegate and then the compiler won't complain anymore. Delegate without any namespace qualification will then resolve to the one from the Delegating namespace. Direct use of System.Delegate and its members is very rare and for those few times where it needs to be used in the same source file where Delegating is being used, one can either use namespace qualification or rename either class.

Ah, nice! I did not know that. There are so many ways to `use` a class...

> As for the options you list for the library user, there is yet another. 

Indeed, I did not consider `using Enumerable = System.Linq.Enumerable`. This looks like the easiest solution. Perhaps this can be documented in the README? This would satisfy at least my usages. Using both `System.Delegate` and `System.Linq.Enumerable` (in a conflicting manner) happened only once in the project I added this dependency, so this workaround is sufficient.

**Comment by atifaziz** [comment]
> Perhaps this can be documented in the README?

Done in 812c2d91597cae431f4f5af8ee607980e07281a7.

**Comment by fsateler** [comment]
On Fri, Jul 28, 2017 at 12:23 PM, Atif Aziz <notifications@github.com>
wrote:

> Perhaps this can be documented in the README?
>
> Done with 812c2d9
> <https://github.com/atifaziz/Delegating/commit/812c2d91597cae431f4f5af8ee607980e07281a7>
>
Awesome, thanks!

-- 

Saludos,
Felipe Sateler
