### ISSUE TITLE
RFE: Implementation for IRegisteredObject

### ISSUE THREAD

**Issue by fsateler** [atifaziz/Delegating#3]
Implementation is fairly simple:

```csharp

    public static partial class Delegate
    {
        public static IRegisteredObject RegisteredObject(Action<bool> onStop) => new DelegatingRegisteredObject(onStop);

        private sealed class DelegatingRegisteredObject : IRegisteredObject
        {
            private Action<bool> OnStop;

            public DelegatingRegisteredObject(Action<bool> onStop)
            {
                if (onStop == null) {
                    throw new ArgumentNullException(nameof(onStop));
                }
                OnStop = onStop;
            }

            public void Stop(bool immediate)
            {
                try {
                    OnStop?.Invoke(immediate);
                }
                finally {
                    OnStop = null;
                    HostingEnvironment.UnregisterObject(this);
                }
            }
        }
    }
```

However, this would add a dependency on `System.Web`.

**Comment by atifaziz** [comment]
> However, this would add a dependency on `System.Web`. 

That's my concern only concern too. While such references have no cost for projects where they are never implicated (not on any code path so never JIT'd), my experience is that people have a distaste for seeing such a reference added in a non-web project. What I can imagine is publishing another library/package as part of this (or another?) project called `Delegating.AspNet` and add the proposed implementation there. Such a library could then become the home for the following `System.Web` candidate interfaces, all of which seem to have only a single method (minus inherited):

- [`System.Web.IHtmlString`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ihtmlstring)
- [`System.Web.SessionState.IPartialSessionState`](https://docs.microsoft.com/en-us/dotnet/api/system.web.sessionstate.ipartialsessionstate)
- [`System.Web.Routing.IRouteConstraint`](https://docs.microsoft.com/en-us/dotnet/api/system.web.routing.irouteconstraint)
- [`System.Web.Routing.IRouteHandler`](https://docs.microsoft.com/en-us/dotnet/api/system.web.routing.iroutehandler)
- [`System.Web.Management.IWebEventCustomEvaluator`](https://docs.microsoft.com/en-us/dotnet/api/system.web.management.iwebeventcustomevaluator)
- [`System.Web.Util.IWebObjectFactory`](https://docs.microsoft.com/en-us/dotnet/api/system.web.util.iwebobjectfactory)
- [`System.Web.UI.ICodeBlockTypeAccessor`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.icodeblocktypeaccessor)
- [`System.Web.UI.IAutoFieldGenerator`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.iautofieldgenerator)
- [`System.Web.UI.IBindableControl`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.ibindablecontrol)
- [`System.Web.UI.IBindableTemplate`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.ibindabletemplate)
- [`System.Web.UI.IControlBuilderAccessor`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.icontrolbuilderaccessor)
- [`System.Web.UI.IHierarchicalEnumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.ihierarchicalenumerable)
- [`System.Web.UI.IParserAccessor`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.iparseraccessor)
- [`System.Web.UI.IPostBackEventHandler`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.ipostbackeventhandler)
- [`System.Web.UI.IResourceUrlGenerator`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.iresourceurlgenerator)
- [`System.Web.UI.ITemplate`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.itemplate)
- [`System.Web.UI.IUrlResolutionService`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.iurlresolutionservice)
- [`System.Web.UI.IUserControlTypeResolutionService`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.iusercontroltyperesolutionservice)
- [`System.Web.UI.WebControls.ICallbackContainer`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.icallbackcontainer)
- [`System.Web.UI.WebControls.ICompositeControlDesignerAccessor`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.icompositecontroldesigneraccessor)
- [`System.Web.UI.WebControls.IPostBackContainer`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.ipostbackcontainer)
- [`System.Web.UI.WebControls.WebParts.IVersioningPersonalizable`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.webparts.iversioningpersonalizable)
- [`System.Web.UI.WebControls.WebParts.IWebActionable`](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.webparts.iwebactionable)
- [`System.Web.ModelBinding.IMetadataAware`](https://docs.microsoft.com/en-us/dotnet/api/system.web.modelbinding.imetadataaware)
- [`System.Web.ModelBinding.IModelNameProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.web.modelbinding.imodelnameprovider)
- [`System.Web.ModelBinding.IUnvalidatedValueProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.web.modelbinding.iunvalidatedvalueprovider)
- [`System.Web.ModelBinding.IValueProviderSource`](https://docs.microsoft.com/en-us/dotnet/api/system.web.modelbinding.ivalueprovidersource)
- [`System.Web.ModelBinding.IModelBinder`](https://docs.microsoft.com/en-us/dotnet/api/system.web.modelbinding.imodelbinder)
- [`System.Web.Hosting.ISuspendibleRegisteredObject`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.isuspendibleregisteredobject)
- [`System.Web.Hosting.IProcessPingCallback`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.iprocesspingcallback)
- [`System.Web.Hosting.IStopListeningRegisteredObject`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.istoplisteningregisteredobject)
- [`System.Web.Hosting.IAppDomainFactory`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.iappdomainfactory)
- [`System.Web.Hosting.IProcessHostPreloadClient`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.iprocesshostpreloadclient)
- [`System.Web.Hosting.IRegisteredObject`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.iregisteredobject)
- [`System.Web.Hosting.IProcessHostFactoryHelper`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.iprocesshostfactoryhelper)
- [`System.Web.Configuration.IConfigMapPathFactory`](https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.iconfigmappathfactory)
- [`System.Web.Compilation.IAssemblyPostProcessor`](https://docs.microsoft.com/en-us/dotnet/api/system.web.compilation.iassemblypostprocessor)

Thoughts?

**Comment by fsateler** [comment]
I think adding a `Delegating.AspNet` package would be useful. However, in the list you mentioned I don't see any interfaces I really want to implement as anonymous objects, other than `IRegisteredObject`, and possibly the `IModelBinder`. That may well be because I don't normally interface directly with the AspNet subsystem, so there may be others I just have not needed to use.

I wonder if creating a library for just one or two interfaces is too much overhead though.

**Comment by atifaziz** [comment]
> I wonder if creating a library for just one or two interfaces is too much overhead though.

The real reason would be to avoid incurring the `System.Web` dependency for projects that don't need it.

**Comment by atifaziz** [comment]
I have published [Delegating.AspNet](https://github.com/atifaziz/Delegating.AspNet) as a new project (with some initial delegated implementations). Feel free to re-open this issue in that project and a PR would be much appreciated too. 😄
