### ISSUE TITLE
Add netstandard2.0 as target

### ISSUE THREAD

**Issue by Arithmomaniac** [atifaziz/Delegating#4]
As per the [cross-platform guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting):

> NET Standard 1.x is distributed as a granular set of NuGet packages, which creates a large package dependency graph and results in developers downloading a lot of packages when building. [...] All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.

**Comment by atifaziz** [comment]
Fair enough. Want to submit a PR if you're itching for this? 😉 Otherwise I think I can get round to this soon-ish.

**Comment by Arithmomaniac** [comment]
I'm not. Just thought it should be filed somewhere 😃
